### ISSUE TITLE
File missing?

### ISSUE THREAD

**Issue by mouse07410** [NationalSecurityAgency/enigma-simulator#2]
```
$ python3 rejewski.py 
Traceback (most recent call last):
  File "rejewski.py", line 8, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
$ 
```

**Comment by ctubbsii** [comment]
The instructions for running seem to be located at: https://github.com/NationalSecurityAgency/enigma-simulator/blob/master/MasterEnigmaCracker.ipynb

It looks like it's intended to be run inside a Jupyter Notebook. Perhaps that is the problem?

**Comment by mouse07410** [comment]
> It looks like it's intended to be run inside a [Jupyter Notebook](https://en.wikipedia.org/wiki/Project_Jupyter#Jupyter_Notebook). Perhaps that is the problem?

Yes, it is twice a problem. 

First, the README doesn't mention this small fact (and I find it plain weird that one must execute interpretable source code in a "web-based interactive environment for creating Jupyter notebook documents", as that's what Jupyter Notebook is, according to Wiki).

Second - I'd recommend making it less dependent on exotic platforms. Some people use "normal" text editors (Emacs, vi, BBedit, etc. - not a web-based monstrosity) and a shell to run the interpretor (python executable). Others prefer a full-fledged IDE like PyCharm, or IDEA with a Python plugin, or Visual Studio Code with a Python plugin. 

Catering for the first group (assume the user has a text editor and a terminal with shell) seems optimal. If you must insert a dependency on some weird software - why not use [IDEA](https://www.jetbrains.com/idea/) (as it has free Community Edition and runs on all the platforms) or [Visual Studio Code](https://code.visualstudio.com/) (as it's free and runs on all the platforms)?

**Comment by daniel-deutscher** [comment]
have you tried pip install tqdm? pip3 install tqdm? apt-get tqdm? or if you are in the jupyter environment since I can see you love it so much try !pip install tqdm.  There is no dependency tied into jupyter that you can't resolve, download these packages and run jupyter nbconvert --to script MasterEnigmaCracker.ipynb in CMD to produce a python script

**Comment by ctubbsii** [comment]
Since a workaround has been suggested to resolve the dependency, I'll close this.
